url: https://quartaeccedente.github.io
baseurl: https://quartaeccedente.github.io
immagine_sfondo_header: img/portfolio/img_corale/mulinaccio.jpg

# Site settings
title: Corale Quarta Eccedente
email: info@quartaeccedente.it
description: "Benvenuti nel sito ufficiale della Corale Quarta Eccedente di Vaiano. Scopri qui il nostro repertorio musicale, i nostri concerti e le nostre performance. Grazie per essere passato a trovarci e a condividere con noi l'emozione della musica corale"


# Team names, titles and social links
people:
- name: Fabio Cavaciocchi
  pic: man
  position: Direttore

- name: Filippo Marinai
  pic: man
  position: Presidente

- name: Daniele Macchioni Montini
  pic: man
  position: Segretario

- name: Arianna Bicchi
  pic: woman
  position: Soprano

- name: Ada Cavaciocchi
  pic: woman
  position: Soprano

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/quarta.eccedente
  - title: instagram
    url: https://www.instagram.com/coralequartaeccedente/
  - title: youtube
    url: https://www.youtube.com/@quartaeccedente

# Postal address (add as many lines as necessary)
Indirizzi utili:
  - Sede: Via Lungobisenzio, 19, 59021 Vaiano (PO)
  - Recapito postale: Via Lungobisenzio, 19, 59021 Vaiano (PO)
  - Sede prove: Scuola Media "Bartolini", Via Vitali, 59021 Vaiano (PO)

# Build settings
markdown: kramdown
permalink: pretty